site_name: Terminal Agency
site_description: Agence WebSite with Mkdocs
site_author: 'Terminal'
site_url: 'https://terminal-agency.github.io/' # Uncomment to set a canonical URL

copyright: |
  &copy; Terminal Agency

docs_dir: docs/

#repo_name: terminal-agency/terminal-agency.github.io
#repo_url: https://github.com/terminal-agency/terminal-agency.github.io.git
#edit_uri: tree/master/docs # Uncomment to define a different URI/URL for the "edit" option

nav:
  - Accueil: index.md
  - À propos: apropos.md
  - Services: services.md
  - Témognages: temognages.md
  - Blog: blog.md
  - Contact: contact.md

theme:
  name: 'material'
  
  #custom_dir: 'theme'
  
  #favicon: /home/noureddine/Escritorio/Projects/I Am Mus./Web Site/logo.png
  
  palette:
  
    scheme: slate
    
    primary: pink
    
    accent: pink
    
  #font:
  #  text: 'Roboto'
  #  code: 'Roboto Mono'
  
  language: fr
  
  #direction: 'ltr'
  
  features:
  # Announce
  #
  - announce.dismiss # Adds a "X" button to dismiss a news banner/mark it as read.*
  
  # Header
  #
  - header.autohide # Hide header when user scrolls past a specific point.
  
  # Navigation:
  #
  - navigation.expand      # Expand all collapsable sections.
  - navigation.instant     # Instant loading pages.
  - navigation.indexes     # Attach pages directly to Sections. Incompatible with "toc.integrate"
  - navigation.sections    # Render top sections as groups.
  - navigation.tabs         # Render top sections as tabs at the top.
  #- navigation.tabs.sticky # Tabs won't disappear when scrolling down. Requires "navigation.tabs".
  - navigation.top         # Adds a "Back to top" that is shown when scrolling up.
  - navigation.tracking    # Updates the url with highlighted section anchor.
  - navigation.path
  # Search
  #
  - search.highlight # Search will highlight the searched word(s) on the page.*
  - search.share     # Adds an option to share a search query link.*
  - search.suggest   # Search will suggest the likeliest completion for a word.*
  
  # Table of Contents
  #
  #- toc.integrate          # Include the TOC sections in the left navugation.
  #- toc.follow

  icon:
    logo: material/text-shadow

  #favicon: ./docs/images/logo.png
  
  admonition:
      note: 'octicons/tag-16'
      abstract: 'octicons/checklist-16'
      info: 'octicons/info-16'
      tip: 'octicons/squirrel-16'
      success: 'octicons/check-16'
      question: 'octicons/question-16'
      warning: 'octicons/alert-16'
      failure: 'octicons/x-circle-16'
      danger: 'octicons/zap-16'
      bug: 'octicons/bug-16'
      example: 'octicons/beaker-16'
      quote: 'octicons/quote-16'

#extra_css:

#extra_javascript:

extra:

  alternate:
    - name: Frençais
      link: https://terminal-agency.github.io/
      lang: fr
    - name: Español
      link: /es/
      lang: es

  consent:
    cookies:
      analytics:
        name: Google Analytics
        checked: false
    actions:
      - accept
      - manage
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

  analytics: 
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

social:
    - icon: 'fontawesome/brands/github'
      link: https://github.com/Nowre/IAmMus.git
    - icon: fontawesome/brands/twitter
      link: https://fosstodon.org/@squidfunk

  generator: false
  
  #manifest: manifest.webmanifest
  
#alternate:

markdown_extensions:
  - markdown.extensions.admonition:
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: true
  #- pymdownx.arithmex:
  #- pymdownx.b64:
  #- pymdownx.betterem:
  #- pymdownx.caret:
  #- pymdownx.critic:
  - pymdownx.details:
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  #- pymdownx.escapeall:
  #- pymdownx.extra:
  #- pymdownx.extrarawhtml:
  #- pymdownx.highlight:
  #- pymdownx.inlinehilite:
  #- pymdownx.keys:
  #- pymdownx.magiclink:
  #- pymdownx.mark:
  #- pymdownx.pathconverter:
  #- pymdownx.progressbar:
  #- pymdownx.smartsymbols:
  #- pymdownx.snippets:
  #- pymdownx.striphtml:
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true 
  #- pymdownx.tasklist:
  #- pymdownx.tilde:

  - attr_list
  - md_in_html